# Generated by Django 5.2.4 on 2025-11-04 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='main_image',
        ),
    ]
