# Generated by Django 5.2.4 on 2025-11-04 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='image',
            field=models.ImageField(default='images/placeholder.png', upload_to='ad_images/'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdImage',
        ),
    ]
