# Generated by Django 5.2.4 on 2025-11-03 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_images/'),
        ),
    ]
