# Generated by Django 5.2.4 on 2025-11-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='main_image',
            field=models.ImageField(blank=True, default='static/media/images/placeholder.png', null=True, upload_to='ad_images/'),
        ),
    ]
