# Generated by Django 5.2.4 on 2025-11-03 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_ad_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='main_image',
            field=models.ImageField(default='images/placeholder.png', upload_to='ad_images/'),
        ),
    ]
