# Generated by Django 5.2.4 on 2025-11-03 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ad_main_image'),
    ]

    operations = [
    ]
