# Generated by Django 5.2.4 on 2025-11-04 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_ad_image_delete_adimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='ad_images/')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='myapp.ad')),
            ],
            options={
                'verbose_name': 'Додаткове зображення',
                'verbose_name_plural': 'Додаткові зображення',
            },
        ),
    ]
