# Generated by Django 5.2.4 on 2025-11-03 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_auto_20251103_1936.py'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ad',
            name='image',  # <--- Це назва колонки, яка викликає помилку
        ),
    ]
