# Generated by Django 5.2.4 on 2025-11-03 13:16

from django.db import migrations,models

class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='AD',
            name='place',
            field=models.CharField(max_length=50, default=''),
            preserve_default=False,
        ),
    ]
