# Generated by Django 5.2.4 on 2025-11-17 20:22

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_chatmessage_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='chat_file'),
        ),
    ]
