# Generated by Django 5.2.4 on 2025-11-03 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_auto_20251103_1609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='adimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='ad_images/'),
        ),
    ]
