# Generated by Django 5.2.4 on 2025-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_delete_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='price',
            field=models.CharField(default='UAH', max_length=15),
        ),
    ]
