# Generated by Django 5.2.4 on 2025-11-06 14:21

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=cloudinary.models.CloudinaryField(default='xoe34jkbrrv8lr7mfpk8', max_length=255, verbose_name='image'),
        ),
    ]
