# Generated by Django 5.2.4 on 2025-11-18 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_ad_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatroom',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_rooms', to='myapp.ad'),
        ),
    ]
